---
- name: feature requested
  description: Request for a feature
  color: 0E8A16
- name: ignore-for-release
  description: Ignore pull request for a new release
  color: ededed
- name: todo
  description: Action we need to perform at some moment
  color: ededed
- name: service
  description: Indicates the scope is related to the own service logic, for example a new feature, bugfix...
  color: ededed
- name: tests
  description: Indicates the scope is related to the tests
  color: ededed
- name: configuration
  description: Indicates the scope is related to the configuration
  color: ededed
- name: build
  description: Indicates the change is related to the build
  color: ededed
- name: CI/CD
  description: Indicates the change is related to CI/CD workflows
  color: ededed
- name: feature
  description: Feature added in the PR
  color: ededed
- name: fix
  description: Fix applied in the PR
  color: ededed
- name: breaking
  description: Breaking change in the PR
  color: ededed
- name: bug
  description: Something isn't working
  color: d73a4a
- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: duplicate
  description: This issue or pull request already exists
  color: cfd3d7
- name: github_actions
  description: Pull requests that update GitHub Actions code
  color: 000000
- name: size/xs
  description: Pull request size XS
  color: ededed
- name: size/s
  description: Pull request size S
  color: ededed
- name: size/m
  description: Pull request size M
  color: ededed
- name: size/l
  description: Pull request size L
  color: ededed
- name: size/xl
  description: Pull request size XL
  color: ededed
