version: "3.8"

services:
  my-service-dev:
    container_name: my-service-dev
    restart: unless-stopped
    env_file: .env # Use a separate file for sensitive variables
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
      - "9229:9229"
    volumes:
      - .:/app
      - node_modules:/app/node_modules/

  db: # New service for the database
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSOWRD} # Replace with a strong password
      POSTGRES_DB: ${DB_NAME} # Set the desired database name
    container_name: komvos-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data

volumes:
  node_modules:
  postgres-data:
