name: 'coverage'
on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test && cp coverage/merge/coverage-final.json report.json
