---
name: 'Node'

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v4
      - name: Cache Dependencies ⌛️
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/workflows/node.yml') }}
      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Install dependencies 📥
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          # Bellow npm install is a workaround for https://github.com/swc-project/swc/issues/5616#issuecomment-1651214641
          npm install --save-optional \
            "@swc/core-darwin-arm64" \
            "@swc/core-darwin-x64" \
            "@swc/core-linux-arm-gnueabihf" \
            "@swc/core-linux-arm64-gnu" \
            "@swc/core-linux-arm64-musl" \
            "@swc/core-linux-x64-gnu" \
            "@swc/core-linux-x64-musl" \
            "@swc/core-win32-arm64-msvc" \
            "@swc/core-win32-ia32-msvc" \
            "@swc/core-win32-x64-msvc"
      - name: Build typescript 📦
        run: npm run build && find dist/main.js
      - name: Lint code 💅
        run: npm run lint
      - name: Run tests ✅
        run: npm run test
